# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86b4dec763f3443e73f0615c95ba31ecc5ae4ce477cf70169f35e07eba334a963996f18e8e1ddf6d9c1e95196e986cdb51c84485385fc3ed715096e3a3c094e7

test:
  secret_key_base: 2be8b2c2e93c360c82ed1841202551d3599dae5d01d2f58a1d8727e2a4d909913a7889a6923ad0294daf8b752fcb5308d4b6ce4f08f1fda50bcda9a32931adfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
