# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cec6fb8860c5adade7143590aacb4dd8e857cf18da290945a5275569ec3f17e4a1a7899382489cb80cc778962300e686a89bd511f3e3aee1c87b9b69a38ec726

test:
  secret_key_base: 9e5d1a030c993e3a4d3398110571c716e759b8b3a16dec5b60c77ba66cc05930a9b0bb52cf9eb961f54b5d24f708521508f73eefcbaaaded48436495285524d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
