Rails.application.routes.draw do

   # form for creating a new high_score
   get 'high_scores/new', to: 'high_scores#new', as: 'new_high_score'

   # editing an existing HighScore object
  get 'high_scores/:id/edit', to: 'high_scores#edit', as: 'edit_high_score'

   # an individual HighScore object
   get 'high_scores/:id', to: 'high_scores#show', as: 'high_score'

   # all HighScore objects
   get 'high_scores', to: 'high_scores#index', as: 'high_scores'

   # after form generated by new is filled out
   # user comes to this page to create the actual object
   post 'high_scores', to: 'high_scores#create'

  # after form generated by edit is filled out
  # user comes to this page to update the actual object
  patch 'high_scores', to: 'high_scores#update'

   root 'high_scores#index'

end
