# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbc71cefb1089fafe45bdb396688bea11cc1612c562080129e10d96e04b1170b0894a78304be501ae298e3572060523b0f06a01b1865528a23290098859b6959

test:
  secret_key_base: 9cd775359ea473aa61d3ddf052a197d99d21ba0ad98ddfc9a41a8148b77bb8575d89673db52dee07f3c484e5c662fc30b92c73f2bc369d31a5f1bacc3f329ad6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
